sudo: required

language: c

compiler:
  - gcc

services:
  - docker

script: 
  - docker build -t $BUILDING .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  
deploy:
  - provider: script
    script: docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_TAG; docker push $DOCKER_IMAGE:$TRAVIS_TAG
    on: 
      tags: true
  - provider: script
    script: docker tag $BUILDING $DOCKER_IMAGE:zeroconf; docker push $DOCKER_IMAGE:zeroconf
    on:
      branch: zeroconf

env:
  global:
    - DOCKER_IMAGE=sudomesh/sudowrt-firmware
    - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT
