sudo: required

language: c

compiler:
  - gcc

services:
  - docker

script: 
  - travis_wait sleep 600 &
  - docker pull $DOCKER_IMAGE:latest
  - docker create --name $DOCKER_CONTAINER $DOCKER_IMAGE:latest
  - docker cp . $DOCKER_CONTAINER:$BUILD_DIR
  - docker start -a  $DOCKER_CONTAINER

after_success:
  - docker commit $DOCKER_CONTAINER $BUILDING
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  
deploy:
  - provider: script
    script: docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_TAG; docker push $DOCKER_IMAGE:$TRAVIS_TAG
    on: 
      tags: true
  - provider: script
    script: docker tag $BUILDING $DOCKER_IMAGE:latest; docker push $DOCKER_IMAGE:latest
    on:
      branch: master

env:
  global:
    - DOCKER_IMAGE=sudomesh/sudowrt-firmware
    - DOCKER_CONTAINER=sudowrt
    - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT
    - BUILD_DIR=$/usr/local/sudowrt-firmware/
