sudo: required

language: c

compiler:
    - gcc

services:
    - docker

script: 
    - docker build -t $BUILDING .
#    - docker run -v $PWD/firmware_images:/firmware_images $BUILDING ar71xx
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_BUILD_ID; 
    docker push $DOCKER_IMAGE:$TRAVIS_BUILD_ID;
    fi
env:
  global:
    - DOCKER_IMAGE=sudowrt/firmware
    - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT

